name: Deploy and Run Script on EC2

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Enter 'hello' or 'Hi'"
        required: true
        default: "hello"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Copy script to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem script.sh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~

      - name: Run script on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@$Ec2LB-1233545415.us-east-1.elb.amazonaws.com << 'EOF'
            chmod +x ~/script.sh
            echo "Running script with input: ${{ github.event.inputs.message }}"
            ~/script.sh ${{ github.event.inputs.message }}
          EOF
